name: anothersite
favicon: null
layout_spectrum: 0.50024
typography_spectrum: 0.07127
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#203221'
    - '#4f7d56'
    - '#9cb281'
    - '#0047b4'
  brandStrength: 0.1875
  lightness: 0.1875
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
